plugins {
    id 'java'
    id 'java-library'
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.7'
    id "org.sonarqube" version "6.0.0.5145"
    id 'com.diffplug.spotless' version '6.21.0'
    id 'org.flywaydb.flyway' version "${flywayVersion}"
    id 'jacoco'
}

allprojects {
    group = 'com.huddey.core'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    if (configurations.findByName("annotationProcessor") != null) {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }
    if (configurations.findByName("developmentOnly") == null) {
        developmentOnly
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonDatatypeVersion}"
    implementation "org.flywaydb:flyway-core:${flywayVersion}"
    implementation "me.paulschwarz:spring-dotenv:${dotenvVersion}"
    implementation "io.jsonwebtoken:jjwt-api:${jwtVersion}"
    runtimeOnly "io.jsonwebtoken:jjwt-impl:${jwtVersion}"
    runtimeOnly "io.jsonwebtoken:jjwt-jackson:${jwtVersion}"
    implementation 'org.postgresql:postgresql'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.testcontainers:testcontainers:1.19.3'
    testImplementation 'org.testcontainers:junit-jupiter:1.19.3'
    testImplementation 'org.testcontainers:postgresql:1.19.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

spotless {
    java {
        target 'src/**/*.java'
        googleJavaFormat('1.25.0')
        removeUnusedImports()
        importOrder('java', 'javax', 'org', 'com')
        trimTrailingWhitespace()
        endWithNewline()
    }
}

tasks.named("build") {
    dependsOn("spotlessCheck")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.matching { it.name == 'prepareKotlinBuildScriptModel' }.configureEach {
    enabled = false
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
    dependsOn test
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}


sonar {
    properties {
        property "sonar.projectKey", "global-jcraft_userman"
        property "sonar.organization", "global-jcraft"
        property "sonar.host.url", "https://sonarcloud.io"
    }
}