# src/main/resources/application-local.yaml
spring:
  application:
    name: userman
  datasource:
    url: jdbc:postgresql://localhost:5432/userman
    username: postgres
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/userman
    user: postgres
    password: dev_password
    default-schema: huddey_userman

server:
  port: 8081