spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - openid
              - email
              - profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v16.0/dialog/oauth
            token-uri: https://graph.facebook.com/v16.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v16.0/me?fields=id,name,email,picture.type(large)
            user-name-attribute: id

  application:
    name: userman
  datasource:
    url: jdbc:postgresql://localhost:5432/userman
    username: postgres
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/userman
    user: postgres
    password: dev_password
    default-schema: huddey_userman
  cloud:
    aws:
      sqs:
        region: us-east-1
        localstack:
          endpoint: http://localhost:4566
          queue:
            name: userman-local-register-event.fifo
            url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/userman-local-register-event.fifo
            fifo: true
            group-id: default-group
            content-based-deduplication: true
        client:
          timeout: 30
          connect-timeout: 10000
          read-timeout: 10000
          write-timeout: 10000


logging:
  level:
    org.springframework.security: DEBUG
    com.huddey.core.userman.auth.oauth2: DEBUG
    io.awspring.cloud: DEBUG
    software.amazon.awssdk: DEBUG
    org.springframework.messaging: DEBUG

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: jcraft
    key-alias: jcraft-local
    key-store-type: PKCS12
  servlet:
    context-path: /userman

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      accessTokenValidity: 3600000  # 1 hour
      refreshTokenValidity: 86400000 # 24 hours
      rememberMeAccessTokenValidity:  432000000 # 5 days
      rememberMeRefreshTokenValidity:  604800000 # 7 days
