# src/main/resources/application-dev.yaml
spring:
  application:
    name: userman
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/userman
    user: postgres
    password: dev_password
    default-schema: huddey_userman

server:
  port: 8081