# src/main/resources/application-dev.yaml
spring:
  application:
    name: userman
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true