version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build the Project
          command: ./gradlew build

  unit-tests:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - store_test_results:
          path: build/test-results/test

  code-quality:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run SonarQube Analysis
          command: gradle build sonarqube

  package:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Package the Application
          command: ./gradlew bootJar
      - store_artifacts:
          path: build/libs/

  docker-build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker build -t docker.io/${DOCKER_USERNAME}/jcraft-userman:latest .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push docker.io/${DOCKER_USERNAME}/jcraft-userman:latest

  deploy-staging:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy to Staging
          command: ./scripts/deploy.sh staging

  deploy-production:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy to Production
          command: ./scripts/deploy.sh production

workflows:
  build-test-deploy:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - code-quality:
          requires:
            - build
          context: SonarCloud
      - package:
          requires:
            - unit-tests
      - docker-build:
          requires:
            - package
      - deploy-staging:
          requires:
            - docker-build
      - deploy-production:
          requires:
            - deploy-staging
